// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9qVAoRpexWtbSZD5bchDP7AExIpRSosw',
    appId: '1:42591754836:web:8e3ea1852755d4fcfe6bc1',
    messagingSenderId: '42591754836',
    projectId: 'sokocat',
    authDomain: 'sokocat.firebaseapp.com',
    storageBucket: 'sokocat.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvaNN4TzgUleg2PxjPdgb1HUU0h8yhCqY',
    appId: '1:42591754836:android:7e0116abfde7a05bfe6bc1',
    messagingSenderId: '42591754836',
    projectId: 'sokocat',
    storageBucket: 'sokocat.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWHBzaYIS87rq-DT-TIrMrzHpwNF8GPEQ',
    appId: '1:42591754836:ios:2ed512fcca64be68fe6bc1',
    messagingSenderId: '42591754836',
    projectId: 'sokocat',
    storageBucket: 'sokocat.firebasestorage.app',
    iosBundleId: 'com.catcafe.catCafeSokoban',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBWHBzaYIS87rq-DT-TIrMrzHpwNF8GPEQ',
    appId: '1:42591754836:ios:2ed512fcca64be68fe6bc1',
    messagingSenderId: '42591754836',
    projectId: 'sokocat',
    storageBucket: 'sokocat.firebasestorage.app',
    iosBundleId: 'com.catcafe.catCafeSokoban',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA9qVAoRpexWtbSZD5bchDP7AExIpRSosw',
    appId: '1:42591754836:web:60e0c8738bba60cbfe6bc1',
    messagingSenderId: '42591754836',
    projectId: 'sokocat',
    authDomain: 'sokocat.firebaseapp.com',
    storageBucket: 'sokocat.firebasestorage.app',
  );

}